version: '3'

services:
  e-feira-app:
    container_name: e-feira-app
    build: .
    volumes:
      - .:/app
    tty: true
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - e-feira-db
    external_links:
      - e-feira-db
    environment:
      WAIT_HOSTS: e-feira-db:5432
      
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  e-feira-db:
    image: postgres:12
    hostname: postgresql
    container_name: e-feira-postgresql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
